version: '3'

services:
  db_redis:
    image: redis
    expose: 
      - "6379"
    ports:
      - "6379:6379"
  db_mysql:
    image: mysql:5.6
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ../smgrdocker/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysitedb
      - MYSQL_ROOT_PASSWORD=123456
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_mysql
      - db_redis
