# Generated by Django 2.0.6 on 2018-10-19 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_received', models.CharField(max_length=20, verbose_name='收到的数据')),
                ('bytes_sent', models.CharField(max_length=20, verbose_name='发送的数据')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SSRAccount', verbose_name='SSR账户')),
            ],
            options={
                'verbose_name_plural': '用户流量使用情况',
                'verbose_name': '用户流量使用情况',
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20, verbose_name='工单状态'),
        ),
    ]
