# Generated by Django 2.0.6 on 2018-06-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='profile_photo',
        ),
    ]
