# Generated by Django 2.0.6 on 2018-10-22 17:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181019_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='交易金额')),
                ('time', models.PositiveIntegerField(verbose_name='购买天数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='交易时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=20, verbose_name='工单状态'),
        ),
    ]
