# Generated by Django 2.0.6 on 2018-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181022_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssraccount',
            old_name='obfs_enable',
            new_name='compatible',
        ),
        migrations.AlterField(
            model_name='ssraccount',
            name='method',
            field=models.CharField(choices=[('none', 'none'), ('rc4', 'rc4'), ('rc4-md5', 'rc4-md5'), ('rc4-md5-6', 'rc4-md5-6'), ('aes-128-ctr', 'aes-128-ctr'), ('aes-192-ctr', 'aes-192-ctr'), ('aes-256-ctr', 'aes-256-ctr'), ('aes-128-cfb', 'aes-128-cfb'), ('aes-192-cfb', 'aes-192-cfb'), ('aes-128-cfb8', 'aes-128-cfb8'), ('aes-192-cfb8', 'aes-192-cfb8'), ('aes-256-cfb8', 'aes-256-cfb8')], default='none', max_length=30, verbose_name='加密方法'),
        ),
        migrations.AlterField(
            model_name='ssraccount',
            name='obfs',
            field=models.CharField(choices=[('plain', 'plain'), ('http_simple', 'http_simple'), ('http_post', 'http_post'), ('tls1.2_ticket_auth', 'tls1.2_ticket_auth')], default='plain', max_length=30, verbose_name='混淆方法'),
        ),
        migrations.AlterField(
            model_name='ssraccount',
            name='protocol',
            field=models.CharField(choices=[('origin', 'origin'), ('auth_sha1_v4', 'auth_sha1_v4'), ('auth_aes128_md5', 'auth_aes128_md5'), ('auth_aes128_sha1', 'auth_aes128_sha1')], default='origin', max_length=30, verbose_name='协议'),
        ),
    ]
