# Generated by Django 2.0.6 on 2018-07-04 23:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180703_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_received', models.CharField(max_length=20, verbose_name='收到的数据')),
                ('bytes_sent', models.CharField(max_length=20, verbose_name='发送的数据')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户流量使用情况',
                'verbose_name': '用户流量使用情况',
            },
        ),
        migrations.CreateModel(
            name='UserModifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_type', models.CharField(choices=[('modify_email', '修改邮箱'), ('modify_password', '修改密码'), ('modify_profile_photo', '修改头像')], max_length=25, verbose_name='修改类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '账号修改记录',
                'verbose_name': '账号修改记录',
            },
        ),
    ]
