# Generated by Django 2.0.6 on 2018-07-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bandwidthusagerecord_usermodifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthusagerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SsrAccount', verbose_name='用户'),
        ),
    ]
