# Generated by Django 2.0.6 on 2018-11-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181104_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=20, verbose_name='工单状态'),
        ),
    ]
