# Generated by Django 2.0.6 on 2018-10-05 20:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181001_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('body', models.TextField(verbose_name='主体')),
            ],
            options={
                'ordering': ('-time',),
                'verbose_name_plural': '系统公告',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coin_nums',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10, null=True, verbose_name='硬币数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='用于计算用户等级', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='经验'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ssr_expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='SSR有效期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ssr_method',
            field=models.CharField(choices=[('aes-256-cfb', 'aes-256-cfb'), ('aes-128-ctr', 'aes-128-ctr'), ('rc4-md5', 'rc4-md5'), ('salsa20', 'salsa20'), ('chacha20', 'chacha20'), ('none', 'none')], max_length=30, null=True, verbose_name='加密方法'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ssr_obfs',
            field=models.CharField(choices=[('plain', 'plain'), ('http_simple', 'http_simple'), ('http_simple_compatible', 'http_simple_compatible'), ('http_post', 'http_post'), ('tls1.2_ticket_auth', 'tls1.2_ticket_auth')], max_length=30, null=True, verbose_name='混淆方法'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ssr_protocol',
            field=models.CharField(choices=[('auth_sha1_v4', 'auth_sha1_v4'), ('auth_aes128_md5', 'auth_aes128_md5'), ('auth_aes128_sha1', 'auth_aes128_sha1'), ('auth_chain_a', 'auth_chain_a'), ('origin', 'origin')], max_length=30, null=True, verbose_name='协议'),
        ),
    ]
