# Generated by Django 2.0.6 on 2018-10-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181005_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ssr_obfs_enable',
            field=models.BooleanField(default=False, verbose_name='是否启用混淆'),
        ),
    ]
